### ISSUE TITLE
这些error是怎么收集回来的？

### ISSUE THREAD

**Issue by libo1106** [soulteary/Error-Tracer#1]

**Comment by soulteary** [comment]
用户onError 事件中，创建img，使用get把消息推回服务器。

**Comment by soulteary** [comment]
[PR #16](https://github.com/soulteary/Error-Tracer/pull/16)：Browser SDK、sendBeacon/fetch 上报
[PR #18](https://github.com/soulteary/Error-Tracer/pull/18)：自动捕获运行时错误、资源错误、Promise rejection
[PR #20](https://github.com/soulteary/Error-Tracer/pull/20)：将 SDK 内嵌并通过 /assets/error-tracer.js 提供
